before_script:
  - sudo apt-get update -qq && sudo apt-get install -y -qq python3 git lua5.1

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - python3 build/lint.py
    - python3 build/buildscript.py
    - python3 build/packAssets.py
    - 'echo "GIT_VERSION = \"$(git rev-parse HEAD)-$(git rev-parse --abbrev-ref HEAD)\"" > vrp_build/buildinfo.lua'
    - "tar czf artifacts.tar.gz [shader] bone_attach exo_maps vrp_build"
    - "tar czf assets.tar.gz vrp_assets"
    - echo $HTTP_ASSETS_SECRET_UPLOAD
    - rm -rf vrp_assets
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - artifacts.tar.gz
      - assets.tar.gz

deploy_job:
  stage: deploy
  script:
    - "echo 'TODO: Upload artifacts'"
    - "echo 'TODO: Upload assets to http server'"
