before_script:
  - sudo docker info
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq python3 git lua5.1 libc6:i386 libz1:i386 libstdc++6:i386

stages:
  - build
  - build_docker
  - deploy
  - clean_env

build_app_job:
  stage: build
  script:
    - 'echo "GIT_VERSION=\"$(git rev-parse HEAD)\" ; GIT_BRANCH=\"$CI_BUILD_REF_NAME\"" >> vrp/buildinfo.lua'
    - python3 build/lint.py
    - python3 build/buildscript.py $CI_BUILD_REF_NAME
    - python3 build/packAssets.py
    - ./build/make_archives.sh
    - rm -rf vrp_assets
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 3 days
    paths:
      - artifacts.tar.gz
      - assets.tar.gz

build_docker_job:
  stage: build_docker
  script:
    - sudo docker build -t exo-rl-mta .
    - sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - sudo docker tag exo-rl-mta $DOCKER_USER/exo-rl-mta:latest-$CI_BUILD_REF_NAME
    - '[ "$CI_BUILD_REF_NAME" == "master" ] && sudo docker tag exo-rl-mta $DOCKER_USER/exo-rl-mta:latest'
    - sudo docker push $DOCKER_USER/exo-rl-mta

deploy_job_develop:
  stage: deploy
  script:
    - curl -F "secret=$ASSETS_UPLOAD_SECRET_KEY" -F "git_branch=$(git rev-parse --abbrev-ref HEAD)" -F asset_archive=@assets.tar.gz https://download.exo-reallife.de/upload.php
    - curl http://192.168.122.20:6000/deploy/mta_develop?APISecret=$DEPLOY_API_SECRET_DEVELOP
  environment:
    name: development
    url: http://mta.exo-reallife.de:20002/
  only:
    - master

clean_env_job:
  stage: clean_env
  script:
    - sudo docker rmi $DOCKER_USER/exo-rl-mta:latest-$CI_BUILD_REF_NAME
    - '[ "$CI_BUILD_REF_NAME" == "master" ] && sudo docker rmi $DOCKER_USER/exo-rl-mta:latest'
    - sudo docker rmi exo-rl-mta
