before_script:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq python3 git lua5.1 libc6:i386 libz1:i386 libstdc++6:i386

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - python3 build/lint.py
    - python3 build/buildscript.py
    - python3 build/packAssets.py
    - 'echo "GIT_VERSION = \"$(git rev-parse HEAD)-$(git rev-parse --abbrev-ref HEAD)\"" > vrp_build/buildinfo.lua'
    - ./build/make_archives.sh
    - rm -rf vrp_assets
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - artifacts.tar.gz
      - assets.tar.gz

deploy_job:
  stage: deploy
  script:
    - "echo 'TODO: Upload artifacts'"
    - "echo 'Uploading assets to http-server...'"
    - curl -F "secret=$ASSETS_UPLOAD_SECRET_KEY" -F "git_branch=$(git rev-parse --abbrev-ref HEAD)" -F asset_archive=@assets.tar.gz https://download.exo-reallife.de/upload.php
  only:
    - release
